ServerSettings:
  ActiveMods: ''
  AllowAnyoneBabyImprintCuddle: true
  AllowFlyerCarryPvE: true
  AllowHideDamageSourceFromLogs: true
  AllowHitMarkers: true
  AllowIntegratedSPlusStructures: true
  AllowRaidDinoFeeding: false
  AllowThirdPersonPlayer: true
  AlwaysAllowStructurePickup: true
  AutoDestroyOldStructuresMultiplier: 1.0
  AutoDestroyStructures: true
  AutoSavePeriodMinutes: 15.0
  DinoCharacterFoodDrainMultiplier: 2.0
  ForceAllStructureLocking: true
  GlobalVoiceChat: true
  HarvestAmountMultiplier: 5.0
  ItemStackSizeMultiplier: 5.0
  KickIdlePlayersPeriod: 3600.0
  ListenServerTetherDistanceMultiplier: 1.0
  MaxTamedDinos: 50000.0
  OverrideOfficialDifficulty: 5.0
  OxygenSwimSpeedStatMultiplier: 1.0
  PerPlatformMaxStructuresMultiplier: 1.0
  PlatformSaddleBuildAreaBoundsMultiplier: 1.0
  PlayerCharacterFoodDrainMultiplier: 0.5
  PlayerCharacterWaterDrainMultiplier: 0.5
  PreventDiseases: true
  PreventTribeAlliances: false
  PvEDinoDecayPeriodMultiplier: 1.0
  RCONEnabled: true
  RCONServerGameLogBuffer: 600.0
  RaidDinoCharacterFoodDrainMultiplier: 1.0
  ServerCrosshair: true
  ServerPassword: ''
  ShowFloatingDamageText: true
  ShowMapPlayerLocation: true
  StructurePickupHoldDuration: 0.5
  StructurePickupTimeAfterPlacement: 30.0
  StructurePreventResourceRadiusMultiplier: 1.0
  TamingSpeedMultiplier: 5.0
  TheMaxStructuresInRange: 10500.0
  TribeNameChangeCooldown: 15.0
  TributeCharacterExpirationSeconds: 432000
  TributeDinoExpirationSeconds: 432000
  TributeItemExpirationSeconds: 432000
  XPMultiplier: 5.0
  noTributeDownloads: false
  serverPVE: true
MessageOfTheDay:
  Duration: 45
  Message: ${MESSAGE_OF_THE_DAY}
/Script/ShooterGame.ShooterGameUserSettings:
  ActiveLingeringWorldTiles: 7
  AmbientSoundVolume: 1.0
  CameraShakeScale: 0.65
  ClientNetQuality: 3
  DOFSettingInterpTime: 0.0
  DisableDefaultCharacterItems: false
  DisableMenuMusic: false
  EmoteKeyBind1: 0
  EmoteKeyBind2: 0
  FOVMultiplier: 1.0
  FullscreenMode: 2
  Gamma1: 2.2
  Gamma2: 3.0
  GraphicsQuality: 1
  GroundClutterDensity: 1.0
  HideItemTextOverlay: true
  HighQualityMaterials: true
  HighQualitySurfaces: true
  LODScalar: 1.0
  LastAutoFavorite: true
  LastConfirmedFullscreenMode: 2
  LastDLCTypeSearchType: -1
  LastJoinedSessionPerCategory: ''
  LastPVESearchType: -1
  LastServerSearchHideFull: false
  LastServerSearchProtected: false
  LastServerSearchType: 0
  LastServerSort: 2
  LastServerSortAsc: true
  LastUserConfirmedResolutionSizeX: 1280
  LastUserConfirmedResolutionSizeY: 720
  LocalCraftingSortType: 0
  LocalItemSortType: 0
  LookLeftRightSensitivity: 1.0
  LookUpDownSensitivity: 1.0
  MacroCtrl0: ''
  MacroCtrl1: ''
  MacroCtrl2: ''
  MacroCtrl3: ''
  MacroCtrl4: ''
  MacroCtrl5: ''
  MacroCtrl6: ''
  MacroCtrl7: ''
  MacroCtrl8: ''
  MacroCtrl9: ''
  MasterAudioVolume: 1.0
  MaxAscensionLevel: 0
  MusicAudioVolume: 1.0
  PlayActionWheelClickSound: true
  RemoteCraftingSortType: 0
  RemoteItemSortType: 0
  ResolutionSizeX: 1280
  ResolutionSizeY: 720
  SFXAudioVolume: 1.0
  ShowExplorerNoteSubtitles: false
  TrueSkyQuality: 0.7
  UIQuickbarScaling: 0.65
  UIScaling: 1.0
  Version: 5
  VersionMetaTag: 1
  VoiceAudioVolume: 1.0
  WindowPosX: -1
  WindowPosY: -1
  bAllowAnimationStaggering: true
  bCameraViewBob: true
  bChatBubbles: true
  bChatShowSteamName: false
  bChatShowTribeName: true
  bCraftablesShowAllItems: false
  bDisableBloom: false
  bDisableLightShafts: false
  bDisableMeleeCameraSwingAnims: false
  bDisableMenuTransitions: false
  bDisableTPVCameraInterpolation: false
  bDisableTorporEffect: false
  bDistanceFieldShadowing: true
  bEnableColorGrading: true
  bEnableInventoryItemTooltips: true
  bExtraLevelStreamingDistance: false
  bFPVClimbingGear: false
  bFPVGlidingGear: false
  bFilmGrain: false
  bFirstPersonRiding: false
  bFloatingNames: true
  bForceTPVCameraOffset: false
  bHideFloatingPlayerNames: false
  bHideGamepadItemSelectionModifier: false
  bHideServerInfo: false
  bHighQualityAnisotropicFiltering: false
  bHighQualityLODs: false
  bHostSessionHasBeenOpened: false
  bInvertLookY: false
  bJoinNotifications: false
  bLocalInventoryCraftingShowAllItems: true
  bLocalInventoryItemsShowAllItems: false
  bLowQualityVFX: false
  bMotionBlur: false
  bNoBloodEffects: false
  bNoTooltipDelay: false
  bPreventColorizedItemNames: false
  bPreventCrosshair: false
  bPreventHitMarkers: false
  bPreventInventoryOpeningSounds: false
  bPreventItemCraftingSounds: false
  bQuickToggleItemNames: true
  bRemoteInventoryCraftingShowAllItems: false
  bRemoteInventoryItemsShowAllItems: false
  bRemoteInventoryShowCraftables: false
  bRemoteInventoryShowEngrams: true
  bReverseTribeLogOrder: false
  bShowChatBox: true
  bShowStatusNotificationMessages: true
  bSpectatorManualFloatingNames: false
  bSuppressAdminIcon: false
  bTemperatureF: false
  bThirdPersonPlayer: false
  bToggleExtendedHUDInfo: false
  bToggleToTalk: false
  bUseDesktopResolutionForFullscreen: false
  bUseDistanceFieldAmbientOcclusion: false
  bUseLowQualityLevelStreaming: true
  bUseOldThirdPersonCameraOffset: false
  bUseOldThirdPersonCameraTrace: false
  bUseSSAO: true
  bUseSimpleDistanceMovement: false
  bUseVSync: false
ScalabilityGroups:
  sg.AntiAliasingQuality: 3
  sg.EffectsQuality: 3
  sg.GroundClutterQuality: 3
  sg.GroundClutterRadius: 10000
  sg.HeightFieldShadowQuality: 3
  sg.IBLQuality: 1
  sg.PostProcessQuality: 3
  sg.ResolutionQuality: 100
  sg.ShadowQuality: 3
  sg.TextureQuality: 3
  sg.TrueSkyQuality: 3
  sg.ViewDistanceQuality: 3
/Script/Engine.GameSession:
  MaxPlayers: 20
/Game/PrimalEarth/CoreBlueprints/TestGameMode.TestGameMode_C:
  bServerGameLogEnabled: true
