/script/shootergame.shootergamemode:
  bAllowUnlimitedRespecs: true
  bUseCorpseLocator: true
  bDisableStructurePlacementCollision: true
  FuelConsumptionIntervalMultiplier: 2.0
  TerminalItemsExpirationTimeSeconds: 432000
  TamedDinoTorporDrainMultiplier: 2.0
  StructureDamageRepairCooldown: 0.0
  CropDecaySpeedMultiplier: 5.0
  CropGrowthSpeedMultiplier: 5.0
  LayEggIntervalMultiplier: 0.2
  MatingIntervalMultiplier: 0.1
  MatingSpeedMultiplier: 5.0
  EggHatchSpeedMultiplier: 5.0
  BabyMatureSpeedMultiplier: 10
  BabyFoodConsumptionSpeedMultiplier: 0.5
  GlobalSpoilingTimeMultiplier: 2
  BabyImprintingStatScaleMultiplier: 2.5
  BabyCuddleIntervalMultiplier: 0.01
  BabyImprintAmountMultiplier: 10000.0
  BabyCuddleGracePeriodMultiplier: 10.0
  BabyCuddleLoseImprintQualitySpeedMultiplier: 0.0
  PlayerCharacterFoodDrainMultiplier: 0.5
  PlayerCharacterWaterDrainMultiplier: 0.5
  SupplyCrateLootQualityMultiplier: 1.5
  OverridePlayerLevelEngramPoints:
    - 0
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 16
    - 24
    - 24
    - 24
    - 24
    - 24
    - 24
    - 24
    - 24
    - 24
    - 24
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
    - 32
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 56
    - 72
    - 72
    - 72
    - 72
    - 72
    - 72
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 80
    - 2
    - 2
    - 2
    - 2
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  ConfigOverrideItemMaxQuantity:
    - (ItemClassString="PrimalItemAmmo_AdvancedBullet_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_AdvancedRifleBullet_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_AdvancedSniperBullet_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_ArrowFlame_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_ArrowStone_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_ArrowTranq_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_CannonBall_C",Quantity=(MaxItemQuantity=10,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_CompoundBowArrow_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_Flamethrower_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_GrapplingHook_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_RefinedTranqDart_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_Rocket_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_SimpleBullet_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_SimpleRifleBullet_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_SimpleShotgunBullet_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemAmmo_TranqDart_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_BeerJar_C",Quantity=(MaxItemQuantity=100,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Berry_Amarberry_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Berry_Azulberry_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Berry_Mejoberry_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Berry_Narcoberry_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Berry_Stimberry_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Berry_Tintoberry_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CactusSap_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CanteenCraftable_C",Quantity=(MaxItemQuantity=5,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CookedLambChop_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CookedMeat_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CookedMeat_Fish_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CookedMeat_Jerky_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CookedPrimeMeat_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CookedPrimeMeat_Fish_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_CookedPrimeMeat_Jerky_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_GachaPod_C",Quantity=(MaxItemQuantity=10,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_HealSoup_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Honey_C",Quantity=(MaxItemQuantity=300,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Mushroom_Aquatic_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Mushroom_Ascerbic_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Mushroom_Auric_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_NamelessVenom_C",Quantity=(MaxItemQuantity=100,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Narcotic_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_RawMeat_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_RawMeat_Fish_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_RawMutton_C",Quantity=(MaxItemQuantity=300,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_RawPrimeMeat_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_RawPrimeMeat_Fish_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_SpoiledMeat_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_StaminaSoup_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Stimulant_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_SweetVeggieCake_C",Quantity=(MaxItemQuantity=100,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Veggie_Citronal_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Veggie_Longgrass_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Veggie_Rockarrot_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_Veggie_Savoroot_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_WaterJarCraftable_C",Quantity=(MaxItemQuantity=5,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_WaterskinCraftable_C",Quantity=(MaxItemQuantity=5,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemConsumable_WyvernMilk_C",Quantity=(MaxItemQuantity=50,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_BlackPearl_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_BlueSap_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Charcoal_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Chitin_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_ChitinPaste_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Clay_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_CommonMushroom_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_CorruptedPolymer_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_CorruptedWood_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Crystal_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Crystal_Primal_C",Quantity=(MaxItemQuantity=50,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Electronics_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Element_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_ElementShard_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Fibers_C",Quantity=(MaxItemQuantity=3000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Flint_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_FracturedGem_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_FungalWood_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Gas_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Gasoline_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Gem_BioLum_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Gem_Element_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Gem_Fertile_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Gunpowder_C",Quantity=(MaxItemQuantity=2500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Hide_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Keratin_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Metal_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_MetalIngot_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Obsidian_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Oil_C",Quantity=(MaxItemQuantity=2500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Pelt_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Polymer_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Polymer_Organic_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_PreservingSalt_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Propellant_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_RawSalt_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_RedSap_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Sand_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Sap_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_ScrapMetal_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_ScrapMetalIngot_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Silicate_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Silicon_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Silk_C",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_SnailPaste_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Sparkpowder_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_SquidOil_C",Quantity=(MaxItemQuantity=2500,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Stone_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Sulfur_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Thatch_C",Quantity=(MaxItemQuantity=2000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Wood_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
    - (ItemClassString="PrimalItemResource_Wool_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=true))
  PerLevelStatsMultiplier_Player[0]: 2
  PerLevelStatsMultiplier_Player[1]: 2
  PerLevelStatsMultiplier_Player[2]: 2
  PerLevelStatsMultiplier_Player[3]: 2
  PerLevelStatsMultiplier_Player[4]: 2
  PerLevelStatsMultiplier_Player[5]: 2
  PerLevelStatsMultiplier_Player[6]: 2
  PerLevelStatsMultiplier_Player[7]: 5
  PerLevelStatsMultiplier_Player[8]: 2
  PerLevelStatsMultiplier_Player[9]: 2
  PerLevelStatsMultiplier_Player[10]: 2
  PerLevelStatsMultiplier_Player[11]: 2
