ServerSettings:
  HarvestAmountMultiplier: 5.0
  TamingSpeedMultiplier: 5.0
  XPMultiplier: 5.0
  OverrideOfficialDifficulty: 5.0
  ShowFloatingDamageText: true
  serverPVE: true
  noTributeDownloads: false
  AllowFlyerCarryPvE: true
  DinoCharacterFoodDrainMultiplier: 2.0
  AllowAnyoneBabyImprintCuddle: true
  AllowRaidDinoFeeding: false
  PreventDiseases: true
  AutoSavePeriodMinutes: 15.0
  AutoDestroyStructures: true
  AutoDestroyOldStructuresMultiplier: 1.0
  ActiveMods: ""
  ShowMapPlayerLocation: true
  AllowThirdPersonPlayer: true
  ServerCrosshair: true
  ServerPassword: ""
  ServerAdminPassword: ${FJORDUR_SERVER_ADMIN_PASS}
  RCONPort: 29158
  TributeItemExpirationSeconds: 432000
  TributeDinoExpirationSeconds: 432000
  TributeCharacterExpirationSeconds: 432000
  TheMaxStructuresInRange: 10500.0
  OxygenSwimSpeedStatMultiplier: 1.0
  StructurePreventResourceRadiusMultiplier: 1.0
  TribeNameChangeCooldown: 15.0
  PlatformSaddleBuildAreaBoundsMultiplier: 1.0
  AlwaysAllowStructurePickup: true
  StructurePickupHoldDuration: 0.5
  AllowIntegratedSPlusStructures: true
  AllowHideDamageSourceFromLogs: true
  RaidDinoCharacterFoodDrainMultiplier: 1.0
  PvEDinoDecayPeriodMultiplier: 1.0
  KickIdlePlayersPeriod: 3600.0
  PerPlatformMaxStructuresMultiplier: 1.0
  ListenServerTetherDistanceMultiplier: 1.0
  MaxPersonalTamedDinos: 300
  MaxTamedDinos: 50000.0
  ItemStackSizeMultiplier: 5.0
  RCONServerGameLogBuffer: 600.0
  AllowHitMarkers: true
  PreventTribeAlliances: false
  RCONEnabled: true
  StructurePickupTimeAfterPlacement: 30.0
  GlobalVoiceChat: true
  DayTimeSpeedScale: 0.5
  ForceAllStructureLocking: true
  PlayerCharacterFoodDrainMultiplier: 0.5
  PlayerCharacterWaterDrainMultiplier: 0.5
  AllowCaveBuildingPvE: true
MessageOfTheDay:
  Message: ${MESSAGE_OF_THE_DAY}
  Duration: 45
/Script/ShooterGame.ShooterGameUserSettings:
  MasterAudioVolume: 1.0
  MusicAudioVolume: 1.0
  SFXAudioVolume: 1.0
  VoiceAudioVolume: 1.0
  UIScaling: 1.0
  UIQuickbarScaling: 0.65
  CameraShakeScale: 0.65
  bFirstPersonRiding: false
  bThirdPersonPlayer: false
  bShowStatusNotificationMessages: true
  TrueSkyQuality: 0.7
  FOVMultiplier: 1.0
  GroundClutterDensity: 1.0
  bFilmGrain: false
  bMotionBlur: false
  bUseDistanceFieldAmbientOcclusion: false
  bUseSSAO: true
  bShowChatBox: true
  bCameraViewBob: true
  bInvertLookY: false
  bFloatingNames: true
  bChatBubbles: true
  bHideServerInfo: false
  bJoinNotifications: false
  bCraftablesShowAllItems: false
  bLocalInventoryItemsShowAllItems: false
  bLocalInventoryCraftingShowAllItems: true
  bRemoteInventoryItemsShowAllItems: false
  bRemoteInventoryCraftingShowAllItems: false
  bRemoteInventoryShowEngrams: true
  LookLeftRightSensitivity: 1.0
  LookUpDownSensitivity: 1.0
  GraphicsQuality: 1
  ActiveLingeringWorldTiles: 7
  ClientNetQuality: 3
  LastServerSearchType: 0
  LastServerSort: 2
  LastPVESearchType: -1
  LastDLCTypeSearchType: -1
  LastServerSortAsc: true
  LastAutoFavorite: true
  LastServerSearchHideFull: false
  LastServerSearchProtected: false
  HideItemTextOverlay: true
  bQuickToggleItemNames: true
  bDistanceFieldShadowing: true
  LODScalar: 1.0
  bToggleToTalk: false
  HighQualityMaterials: true
  HighQualitySurfaces: true
  bTemperatureF: false
  bDisableTorporEffect: false
  bChatShowSteamName: false
  bChatShowTribeName: true
  bReverseTribeLogOrder: false
  EmoteKeyBind1: 0
  EmoteKeyBind2: 0
  bNoBloodEffects: false
  bLowQualityVFX: false
  bSpectatorManualFloatingNames: false
  bSuppressAdminIcon: false
  bUseSimpleDistanceMovement: false
  bDisableMeleeCameraSwingAnims: false
  bHighQualityAnisotropicFiltering: false
  bUseLowQualityLevelStreaming: true
  bPreventInventoryOpeningSounds: false
  bPreventItemCraftingSounds: false
  bPreventHitMarkers: false
  bPreventCrosshair: false
  bPreventColorizedItemNames: false
  bHighQualityLODs: false
  bExtraLevelStreamingDistance: false
  bEnableColorGrading: true
  DOFSettingInterpTime: 0.0
  bDisableBloom: false
  bDisableLightShafts: false
  LastJoinedSessionPerCategory: ""
  bDisableMenuTransitions: false
  bEnableInventoryItemTooltips: true
  bRemoteInventoryShowCraftables: false
  bNoTooltipDelay: false
  LocalItemSortType: 0
  LocalCraftingSortType: 0
  RemoteItemSortType: 0
  RemoteCraftingSortType: 0
  VersionMetaTag: 1
  ShowExplorerNoteSubtitles: false
  DisableMenuMusic: false
  DisableDefaultCharacterItems: false
  bHideFloatingPlayerNames: false
  bHideGamepadItemSelectionModifier: false
  bToggleExtendedHUDInfo: false
  PlayActionWheelClickSound: true
  MaxAscensionLevel: 0
  bHostSessionHasBeenOpened: false
  bForceTPVCameraOffset: false
  bDisableTPVCameraInterpolation: false
  bFPVClimbingGear: false
  bFPVGlidingGear: false
  Gamma1: 2.2
  Gamma2: 3.0
  AmbientSoundVolume: 1.0
  bAllowAnimationStaggering: true
  bUseOldThirdPersonCameraTrace: false
  bUseOldThirdPersonCameraOffset: false
  bLowQualityAnimations: true
  bUseVSync: false
  MacroCtrl0: ""
  MacroCtrl1: ""
  MacroCtrl2: ""
  MacroCtrl3: ""
  MacroCtrl4: ""
  MacroCtrl5: ""
  MacroCtrl6: ""
  MacroCtrl7: ""
  MacroCtrl8: ""
  MacroCtrl9: ""
  ResolutionSizeX: 1280
  ResolutionSizeY: 720
  LastUserConfirmedResolutionSizeX: 1280
  LastUserConfirmedResolutionSizeY: 720
  WindowPosX: -1
  WindowPosY: -1
  bUseDesktopResolutionForFullscreen: false
  FullscreenMode: 2
  LastConfirmedFullscreenMode: 2
  Version: 5
ScalabilityGroups:
  sg.ResolutionQuality: 100
  sg.ViewDistanceQuality: 3
  sg.AntiAliasingQuality: 3
  sg.ShadowQuality: 3
  sg.PostProcessQuality: 3
  sg.TextureQuality: 3
  sg.EffectsQuality: 3
  sg.TrueSkyQuality: 3
  sg.GroundClutterQuality: 3
  sg.IBLQuality: 1
  sg.HeightFieldShadowQuality: 3
  sg.GroundClutterRadius: 10000
SessionSettings:
  SessionName: ${FJORDUR_SESSION_NAME}
/Script/Engine.GameSession:
  MaxPlayers: 20
/Game/PrimalEarth/CoreBlueprints/TestGameMode.TestGameMode_C:
  bServerGameLogEnabled: true
  ConfigOverrideSupplyCrateItems:
    - '(SupplyCrateClassString="SupplyCrate_Cave_QualityTier1_EX",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.900000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="SupplyCrate_Cave_QualityTier2_EX",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.900000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="SupplyCrate_Cave_QualityTier3_EX",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.900000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="DinoDropInventoryComponent_Beyla",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=3.000000,MaxQuality=7.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.250000,ChanceToActuallyGiveItem=0.100000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="DinoDropInventoryComponent_Hati",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=3.000000,MaxQuality=7.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.250000,ChanceToActuallyGiveItem=0.100000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="DinoDropInventoryComponent_Skoll",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=3.000000,MaxQuality=7.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.250000,ChanceToActuallyGiveItem=0.100000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="DinoDropInventoryComponent_Steinbjorn",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=3.000000,MaxQuality=7.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.250000,ChanceToActuallyGiveItem=0.100000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="SupplyCrate_Space_05_Obsidian",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,MaxQuality=4.300000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.125000,ChanceToActuallyGiveItem=0.300000)),SetWeight=0.002500,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="SupplyCrate_Ruins_LostIsland",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,MaxQuality=1.200000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.800000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="DinoDropInventoryComponent_WorldBoss_10Items",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=3.000000,MaxQuality=7.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.400000)),SetWeight=0.024000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="DinoDropInventoryComponent_WorldBoss_5Items",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=3.000000,MaxQuality=7.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.400000)),SetWeight=0.024000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="SupplyCrate_OceanDrop_Fjordor",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,MaxQuality=1.100000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.900000)),SetWeight=0.015000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="SupplyCrate_IceCaveTier3_Fjordor",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,MaxQuality=1.200000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.500000)),SetWeight=0.190000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="DinoDropInventoryComponent_LavaGolem_jackson",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=3.000000,MaxQuality=7.000000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.300000)),SetWeight=0.022000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="PrimalInventoryBP_GenericFishing",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.400000,RequiresMinQuality=3.000000)),SetWeight=0.001500,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
    - '(SupplyCrateClassString="SupplyCrate_IceCaveTier3",MinItemSets=0,MaxItemSets=1,NumItemSetsPower=0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Седло
      для Кархародонтозавра",ItemEntries=((ItemEntryName="Чертежи: Сёдла",Items=(BlueprintGeneratedClass''/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C''),MinQuantity=1.000000,MinQuality=1.000000,MaxQuality=1.200000,bForceBlueprint=False,ChanceToBeBlueprintOverride=0.500000,ChanceToActuallyGiveItem=0.900000)),SetWeight=0.023000,bItemsRandomWithoutReplacement=True)),bAppendItemSets=True,bAppendPreventIncreasingMinMaxItemSets=False)'
