ServerSettings:
  HarvestAmountMultiplier: 5.0
  TamingSpeedMultiplier: 5.0
  XPMultiplier: 5.0
  OverrideOfficialDifficulty: 5.0
  ShowFloatingDamageText: true
  serverPVE: true
  noTributeDownloads: false
  AllowFlyerCarryPvE: true
  DinoCharacterFoodDrainMultiplier: 2.0
  AllowAnyoneBabyImprintCuddle: true
  AllowRaidDinoFeeding: false
  PreventDiseases: true
  AutoSavePeriodMinutes: 15.0
  AutoDestroyStructures: true
  AutoDestroyOldStructuresMultiplier: 1.0
  ActiveMods: ""
  ShowMapPlayerLocation: true
  AllowThirdPersonPlayer: true
  ServerCrosshair: true
  ServerPassword: ""
  ServerAdminPassword: ${GEN_1_SERVER_ADMIN_PASS}
  RCONPort: ${GEN_1_RCON_PORT}
  TributeItemExpirationSeconds: 432000
  TributeDinoExpirationSeconds: 432000
  TributeCharacterExpirationSeconds: 432000
  TheMaxStructuresInRange: 10500.0
  OxygenSwimSpeedStatMultiplier: 1.0
  StructurePreventResourceRadiusMultiplier: 1.0
  TribeNameChangeCooldown: 15.0
  PlatformSaddleBuildAreaBoundsMultiplier: 1.0
  AlwaysAllowStructurePickup: true
  StructurePickupHoldDuration: 0.5
  AllowIntegratedSPlusStructures: true
  AllowHideDamageSourceFromLogs: true
  RaidDinoCharacterFoodDrainMultiplier: 1.0
  PvEDinoDecayPeriodMultiplier: 1.0
  KickIdlePlayersPeriod: 3600.0
  PerPlatformMaxStructuresMultiplier: 1.0
  ListenServerTetherDistanceMultiplier: 1.0
  MaxPersonalTamedDinos: 300
  MaxTamedDinos: 50000.0
  ItemStackSizeMultiplier: 5.0
  RCONServerGameLogBuffer: 600.0
  AllowHitMarkers: true
  PreventTribeAlliances: false
  RCONEnabled: true
  StructurePickupTimeAfterPlacement: 30.0
  GlobalVoiceChat: true
  DayTimeSpeedScale: 0.5
  AllowTekSuitPowersInGenesis: true
  ForceAllStructureLocking: true
  MaxHexagonsPerCharacter: 5000000
  PlayerCharacterFoodDrainMultiplier: 0.5
  PlayerCharacterWaterDrainMultiplier: 0.5
MessageOfTheDay:
  Message: ${MOTD}
  Duration: 45
/Script/ShooterGame.ShooterGameUserSettings:
  MasterAudioVolume: 1.0
  MusicAudioVolume: 1.0
  SFXAudioVolume: 1.0
  VoiceAudioVolume: 1.0
  CharacterAudioVolume: 1.0
  UIScaling: 1.0
  UIQuickbarScaling: 0.65
  CameraShakeScale: 0.65
  bFirstPersonRiding: false
  bThirdPersonPlayer: false
  bInventoryHideUnlearnedEngrams: false
  bShowStatusNotificationMessages: true
  TrueSkyQuality: 0.7
  FOVMultiplier: 1.0
  GroundClutterDensity: 1.0
  bFilmGrain: false
  bMotionBlur: false
  bUseDistanceFieldAmbientOcclusion: false
  bUseSSAO: true
  bShowChatBox: true
  bCameraViewBob: true
  bInvertLookY: false
  bFloatingNames: true
  bChatBubbles: true
  bHideServerInfo: false
  bJoinNotifications: false
  bCraftablesShowAllItems: false
  bLocalInventoryItemsShowAllItems: false
  bLocalInventoryCraftingShowAllItems: true
  bRemoteInventoryItemsShowAllItems: false
  bRemoteInventoryCraftingShowAllItems: false
  bRemoteInventoryShowEngrams: true
  bForceDisableSuperDetailMode: true
  LookLeftRightSensitivity: 1.0
  LookUpDownSensitivity: 1.0
  GraphicsQuality: 1
  ActiveLingeringWorldTiles: 7
  ClientNetQuality: 3
  LastServerSearchType: 0
  LastServerSort: 2
  LastPVESearchType: -1
  LastDLCTypeSearchType: -1
  LastServerSortAsc: true
  LastAutoFavorite: true
  LastServerSearchHideFull: false
  LastServerSearchProtected: false
  LastServerSearchIncludeServersWithActiveMods: true
  HideItemTextOverlay: true
  bQuickToggleItemNames: true
  bDistanceFieldShadowing: true
  LODScalar: 1.0
  bToggleToTalk: false
  HighQualityMaterials: true
  HighQualitySurfaces: true
  bTemperatureF: false
  bDisableTorporEffect: false
  bChatShowSteamName: false
  bChatShowTribeName: true
  bReverseTribeLogOrder: false
  EmoteKeyBind1: 0
  EmoteKeyBind2: 0
  bNoBloodEffects: false
  bLowQualityVFX: false
  bSpectatorManualFloatingNames: false
  bSuppressAdminIcon: false
  bUseSimpleDistanceMovement: false
  bDisableMeleeCameraSwingAnims: false
  bHighQualityAnisotropicFiltering: false
  bUseLowQualityLevelStreaming: true
  bPreventInventoryOpeningSounds: false
  bPreventItemCraftingSounds: false
  bPreventHitMarkers: false
  bPreventCrosshair: false
  bPreventColorizedItemNames: false
  bHighQualityLODs: false
  bExtraLevelStreamingDistance: false
  bEnableColorGrading: true
  DOFSettingInterpTime: 0.0
  bDisableBloom: false
  bDisableLightShafts: false
  LastJoinedSessionPerCategory: ""
  bDisableMenuTransitions: false
  bEnableInventoryItemTooltips: true
  bRemoteInventoryShowCraftables: false
  bNoTooltipDelay: false
  LocalItemSortType: 0
  LocalCraftingSortType: 0
  RemoteItemSortType: 0
  RemoteCraftingSortType: 0
  VersionMetaTag: 1
  ShowExplorerNoteSubtitles: false
  DisableMenuMusic: false
  DisableDefaultCharacterItems: false
  bRequestDefaultCharacterItemsOnce: false
  bHasSeenGen2Intro: false
  bHideFloatingPlayerNames: false
  bHideGamepadItemSelectionModifier: false
  bToggleExtendedHUDInfo: false
  PlayActionWheelClickSound: true
  CompanionReactionVerbosity: 3
  EnableEnvironmentalReactions: true
  EnableRespawnReactions: true
  EnableDeathReactions: true
  EnableSayHelloReactions: true
  EnableEmoteReactions: true
  EnableMovementSounds: true
  DisableSubtitles: false
  CompanionSubtitleVerbosityLevel: 3
  CompanionIsHiddenState: false
  MaxAscensionLevel: 0
  bHostSessionHasBeenOpened: false
  bForceTPVCameraOffset: false
  bDisableTPVCameraInterpolation: false
  bFPVClimbingGear: false
  bFPVGlidingGear: false
  Gamma1: 2.2
  Gamma2: 3.0
  AmbientSoundVolume: 1.0
  bAllowAnimationStaggering: true
  bUseOldThirdPersonCameraTrace: false
  bUseOldThirdPersonCameraOffset: false
  bLowQualityAnimations: false
  bShowedGenesisDLCBackground: false
  bShowedGenesis2DLCBackground: false
  bViewedAnimatedSeriesTrailer: false
  bViewedARK2Trailer: false
  bShowRTSKeyBinds: true
  bHasCompletedGen2: false
  StopExplorerNoteAudioOnClose: false
  bUseVSync: false
  MacroCtrl0: ""
  MacroCtrl1: ""
  MacroCtrl2: ""
  MacroCtrl3: ""
  MacroCtrl4: ""
  MacroCtrl5: ""
  MacroCtrl6: ""
  MacroCtrl7: ""
  MacroCtrl8: ""
  MacroCtrl9: ""
  ResolutionSizeX: 1280
  ResolutionSizeY: 720
  LastUserConfirmedResolutionSizeX: 1280
  LastUserConfirmedResolutionSizeY: 720
  WindowPosX: -1
  WindowPosY: -1
  bUseDesktopResolutionForFullscreen: false
  FullscreenMode: 2
  LastConfirmedFullscreenMode: 2
  Version: 5
ScalabilityGroups:
  sg.ResolutionQuality: 100
  sg.ViewDistanceQuality: 3
  sg.AntiAliasingQuality: 3
  sg.ShadowQuality: 3
  sg.PostProcessQuality: 3
  sg.TextureQuality: 3
  sg.EffectsQuality: 3
  sg.TrueSkyQuality: 3
  sg.GroundClutterQuality: 3
  sg.IBLQuality: 1
  sg.HeightFieldShadowQuality: 3
  sg.GroundClutterRadius: 10000
SessionSettings:
  SessionName: ${GEN_1_SESSION_NAME}
/Script/Engine.GameSession:
  MaxPlayers: 20
/Game/PrimalEarth/CoreBlueprints/TestGameMode.TestGameMode_C:
  bServerGameLogEnabled: true
  ConfigOverrideSupplyCrateItems: !include ConfigOverrideSupplyCrateItems.yml
  bIgnoreStructuresPreventionVolumes: true
