/script/shootergame.shootergamemode:
  bPassiveDefensesDamageRiderlessDinos: true
  bAllowUnlimitedRespecs: true
  bUseCorpseLocator: true
  bDisableStructurePlacementCollision: true
  FuelConsumptionIntervalMultiplier: 2.0
  CropDecaySpeedMultiplier: 5.0
  CropGrowthSpeedMultiplier: 5.0
  LayEggIntervalMultiplier: 0.2
  MatingIntervalMultiplier: 0.1
  MatingSpeedMultiplier: 5.0
  EggHatchSpeedMultiplier: 5.0
  BabyMatureSpeedMultiplier: 10.0
  BabyFoodConsumptionSpeedMultiplier: 0.25
  GlobalSpoilingTimeMultiplier: 2.0
  BabyImprintingStatScaleMultiplier: 2.5
  BabyCuddleIntervalMultiplier: 0.03
  BabyImprintAmountMultiplier: 10000.0
  BabyCuddleGracePeriodMultiplier: 10.0
  BabyCuddleLoseImprintQualitySpeedMultiplier: 0.0
  PlayerCharacterFoodDrainMultiplier: 0.5
  PlayerCharacterWaterDrainMultiplier: 0.5
  SupplyCrateLootQualityMultiplier: 3.5
  OverridePlayerLevelEngramPoints: !include OverridePlayerLevelEngramPoints.yml
  ConfigOverrideItemMaxQuantity: !include ConfigOverrideItemMaxQuantity.yml
  # 0 - Health
  PerLevelStatsMultiplier_Player[0]: 1.0
  # 1 - Stamina / Charge Capacity
  PerLevelStatsMultiplier_Player[1]: 2.0
  # 2 - Torpidity
  PerLevelStatsMultiplier_Player[2]: 2.0
  # 3 - Oxygen / Charge Regeneration
  PerLevelStatsMultiplier_Player[3]: 2.0
  # 4 - Food
  PerLevelStatsMultiplier_Player[4]: 2.0
  # 5 - Water
  PerLevelStatsMultiplier_Player[5]: 2.0
  # 6 - Temperature
  PerLevelStatsMultiplier_Player[6]: 2.0
  # 7 - Weight
  PerLevelStatsMultiplier_Player[7]: 6.0
  # 8 - Melee Damage / Charge Emission Range
  PerLevelStatsMultiplier_Player[8]: 1.0
  # 9 - Movement Speed / Maewing's Nursing Effectiveness
  PerLevelStatsMultiplier_Player[9]: 1.0
  # 10 - Fortitude
  PerLevelStatsMultiplier_Player[10]: 2.0
  # 11 - Crafting Skill
  PerLevelStatsMultiplier_Player[11]: 2.0
  # 7 - Weight
  PerLevelStatsMultiplier_DinoTamed[7]: 3.5
  UseCorpseLifeSpanMultiplier: 4.0
