- NPCSpawnEntriesContainerClassString: "Ext_DinoSpawnEntries_Forest_C"
  NPCSpawnEntries:
    - AnEntryName: "Ext_Sinomacrops_Forest"
      EntryWeight: 0.1
      NPCsToSpawnStrings:
        - "Sinomacrops_Character_BP_C"
  NPCSpawnLimits:
    - NPCClassString: "Sinomacrops_Character_BP_C"
      MaxPercentageOfDesiredNumToAllow: 0.1
