- NPCSpawnEntriesContainerClassString: "Ext_DinoSpawnEntries_Forest_C"
  NPCSpawnEntries:
    - AnEntryName: "Ext_Sinomacrops_Forest"
      NPCsToSpawnStrings:
        - "Sinomacrops_Character_BP_C"
      NPCsToSpawnPercentageChance:
        - 0.7
      EntryWeight: 0.7
  NPCSpawnLimits:
    - NPCClassString: "Sinomacrops_Character_BP_C"
      MaxPercentageOfDesiredNumToAllow: 0.3
