- NPCSpawnEntriesContainerClassString: "DinoSpawnEntriesSwamp_C"
  NPCSpawnEntries:
    - AnEntryName: "Ragnarok_Rhynio_Swamp"
      NPCsToSpawnStrings:
        - "Rhynio_Character_BP_C"
      NPCsToSpawnPercentageChance:
        - 0.01
      EntryWeight: 0.01
  NPCSpawnLimits:
    - NPCClassString: "Rhynio_Character_BP_C"
      MaxPercentageOfDesiredNumToAllow: 0.01
