- SupplyCrateClassString: SupplyCrate_Cave_QualityTier1_EX
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.9
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: SupplyCrate_Cave_QualityTier2_EX
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.9
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: SupplyCrate_Cave_QualityTier3_EX
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.9
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: DinoDropInventoryComponent_Beyla
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 3.0
          MaxQuality: 7.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.25
          ChanceToActuallyGiveItem: 0.1
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: DinoDropInventoryComponent_Hati
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 3.0
          MaxQuality: 7.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.25
          ChanceToActuallyGiveItem: 0.1
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: DinoDropInventoryComponent_Skoll
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 3.0
          MaxQuality: 7.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.25
          ChanceToActuallyGiveItem: 0.1
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: DinoDropInventoryComponent_Steinbjorn
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 3.0
          MaxQuality: 7.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.25
          ChanceToActuallyGiveItem: 0.1
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: SupplyCrate_Space_05_Obsidian
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          MaxQuality: 4.3
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.125
          ChanceToActuallyGiveItem: 0.3
      SetWeight: 0.0025
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: SupplyCrate_Ruins_LostIsland
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          MaxQuality: 1.2
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.8
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: DinoDropInventoryComponent_WorldBoss_10Items
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 3.0
          MaxQuality: 7.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.4
      SetWeight: 0.024
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: DinoDropInventoryComponent_WorldBoss_5Items
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 3.0
          MaxQuality: 7.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.4
      SetWeight: 0.024
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: SupplyCrate_OceanDrop_Fjordor
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          MaxQuality: 1.1
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.9
      SetWeight: 0.015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: SupplyCrate_IceCaveTier3_Fjordor
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          MaxQuality: 1.2
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.5
      SetWeight: 0.19
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: DinoDropInventoryComponent_LavaGolem_jackson
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 3.0
          MaxQuality: 7.0
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.3
      SetWeight: 0.022
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: PrimalInventoryBP_GenericFishing
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.4
          RequiresMinQuality: 3.0
      SetWeight: 0.0015
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
- SupplyCrateClassString: SupplyCrate_IceCaveTier3
  MinItemSets: 0
  MaxItemSets: 1
  NumItemSetsPower: 0
  bSetsRandomWithoutReplacement: true
  ItemSets:
    - SetName: "Седло для Кархародонтозавра"
      ItemEntries:
        - ItemEntryName: "Чертежи: Сёдла"
          Items:
            - /Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarchaSaddle.PrimalItemArmor_CarchaSaddle_C
          MinQuantity: 1.0
          MinQuality: 1.0
          MaxQuality: 1.2
          bForceBlueprint: false
          ChanceToBeBlueprintOverride: 0.5
          ChanceToActuallyGiveItem: 0.9
      SetWeight: 0.023
      bItemsRandomWithoutReplacement: true
  bAppendItemSets: true
  bAppendPreventIncreasingMinMaxItemSets: false
